# Generated by Django 3.1.3 on 2020-11-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField(null=True)),
                ('poster', models.ImageField(upload_to='posters/e<built-in function id>')),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
