# Generated by Django 3.1.3 on 2020-11-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201105_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('birth_year', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=32, null=True)),
                ('team', models.CharField(max_length=32, null=True)),
                ('grade', models.CharField(choices=[('BR', 'б/р'), ('3Y', '3 ю.р.'), ('2Y', '2 ю.р.'), ('1Y', '1 ю.р.'), ('3C', '3 сп.р.'), ('2C', '2 сп.р.'), ('1C', '1 сп.р.'), ('KMS', 'КМС'), ('MS', 'МС'), ('MSMK', 'МСМК')], default='BR', max_length=4)),
            ],
        ),
    ]
