# Generated by Django 3.1.3 on 2020-11-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='events.event'),
            preserve_default=False,
        ),
    ]
