# Generated by Django 3.1.3 on 2020-11-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201106_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_enter_result_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_results_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='routes_num',
            field=models.IntegerField(null=True),
        ),
    ]
