# Generated by Django 3.1.3 on 2020-11-05 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201106_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='accent',
        ),
        migrations.CreateModel(
            name='Accent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent', models.CharField(choices=[('NO', '-'), ('FL', 'FLASH'), ('RP', 'REDPOINT')], default='NO', max_length=2)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accent', to='events.participant')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accent', to='events.route')),
            ],
        ),
    ]
