# Generated by Django 3.1.3 on 2020-11-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20201106_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='participant',
        ),
    ]
