# Generated by Django 3.1.3 on 2020-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_participant_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
