# Generated by Django 3.1.3 on 2020-11-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_participant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='score_type',
            field=models.CharField(choices=[('SUM', 'Сумма баллов'), ('PROP', 'От кол-ва пролазов')], default='SUM', max_length=4),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_entered_result',
            field=models.BooleanField(default=False),
        ),
    ]
