# Generated by Django 3.1.3 on 2020-11-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20201106_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flash_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='redpoint_points',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='route',
            name='points',
            field=models.FloatField(default=1),
        ),
    ]
