# Generated by Django 3.1.3 on 2020-11-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20201107_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='event',
            name='redpoint_points',
            field=models.IntegerField(default=80),
        ),
    ]
