# Generated by Django 3.1.3 on 2021-02-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_participant_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='points',
            new_name='points_female',
        ),
        migrations.AddField(
            model_name='route',
            name='points_male',
            field=models.FloatField(default=1),
        ),
    ]
